var actions_array = [];
var activity;
var activities = [];
var item;
var itens = [];
var contexto;
var opened = false;
var plano;
var planos = [];
var ciclo;
var ciclos = [];
var cicloEntidade;
var ciclosEntidade = [];
var pilarCiclo;
var pilaresCiclo = [];
var elementoComponente;
var elementosComponente = [];
var componentePilar;
var componentesPilar = [];
var jurisdicao;
var jurisdicoes = [];
var membro;
var membros = [];
