"INSERT INTO jurisdicoes (entidade_id, escritorio_id) "+ "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'ABBOTTPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'ABBPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'ACEPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'ACIPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'ACOS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'AEROS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'AERUS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'AGPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'AGROS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'AKZOPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'ALBAPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'ALCANPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'ALCOA PREVI' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERPE' AND a.sigla = 'ALEPEPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'ALLERGAN PREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'ALPAPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'ALPHA' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERPE' AND a.sigla = 'ALPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'ALSTOM' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERDF' AND a.sigla = 'ANABBPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'APCDPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'APREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'ARM PREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'ARUS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'ATLANTIC' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'ATTILIO FONTANA' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'AUTOLATINA' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'AVELINO' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'AVONPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'AZENPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'B - D PREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERPE' AND a.sigla = 'BANDEPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'BANESES' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'BANESPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERPE' AND a.sigla = 'BANORTE' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'BANRISUL/FBSS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'BASES' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'BASF PC' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'BAYERPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERDF' AND a.sigla = 'BB PREVIDENCIA' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'BCO. SUMITOMO' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'BCPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'BELAUTO' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERPE' AND a.sigla = 'BERONPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'BETZDEARBORN' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'BIEMPRESARIAL' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'BIPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'BLS PREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'BOAVISTAPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERPE' AND a.sigla = 'BOMPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'BOSCHPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'BOSTONPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'BOTICARIO PREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'BP PREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'BRASILETROS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'BRASLIGHT' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'BRASPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'BRF PREVIDÊNCIA' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'BRISTOL-MYERS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'BUNGEPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'CABEA' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERPE' AND a.sigla = 'CABEC' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'CAEMI' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'CAFBEP' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERPE' AND a.sigla = 'CAGEPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'CANADA LIFE' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'CAPAF' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERPE' AND a.sigla = 'CAPEB' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERPE' AND a.sigla = 'CAPEF' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'CAPESESP' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERPE' AND a.sigla = 'CAPOF' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'CARBOPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'CARFEPE' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'CARGILLPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'CARREFOURPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERDF' AND a.sigla = 'CARTAPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'CASANPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'CASFAM' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'CAVA' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'CBS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'CELOS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERPE' AND a.sigla = 'CELPOS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERDF' AND a.sigla = 'CENTRUS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'CENTRUS/MT' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'CEPLUS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERPE' AND a.sigla = 'CE-PREVCOM' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERDF' AND a.sigla = 'CERES' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'CIASPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERDF' AND a.sigla = 'CIBRIUS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'CIC-PREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'CIFRAO' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'CISPER PP' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'CITIPREVI' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'COHAPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERPE' AND a.sigla = 'COMPESAPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'COMSHELL' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'CORRENTE' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'CP PREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'CREDIPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'CREMERPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'CRYOVAC' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'CURITIBAPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'CYAMPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'DANAPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'DAREXPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'DATUSPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'DCPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'DERMINAS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'DESBAN' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERDF' AND a.sigla = 'DF-PREVICOM' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'DIVERPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'DURATEX' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'EATONPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'ECONOMUS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'ECOS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'EDS PREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'ELANCO PREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'ELBA' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'ELETRA' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'ELETROS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'ELOS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'EMBRAER PREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'ENERGISAPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'ENERPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'ENERSUL' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERPE' AND a.sigla = 'EQTPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'ESCELSOS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'F.GUIMARAES' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'FABASA' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'FABRI' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERPE' AND a.sigla = 'FACEAL' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERDF' AND a.sigla = 'FACEB' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERPE' AND a.sigla = 'FACEPI' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERPE' AND a.sigla = 'FACHESF' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'FACOPAC' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'FAECES' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'FAELBA' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERPE' AND a.sigla = 'FAELCE' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'FAIRPLAN' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'FAMILIA PREVIDENCIA' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'FAPA' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERPE' AND a.sigla = 'FAPECE' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'FAPERS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'FAPES' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'FAPIEB' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'FASASS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'FASBEMGE' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'FASC' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERPE' AND a.sigla = 'FASERN' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'FATL' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'FBEMGEPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERDF' AND a.sigla = 'FBRTPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'FEMCO' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'FENIPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'FFMB' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'FGV-PREVI' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'FIBERGLAS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'FIBRA' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'FIOPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERDF' AND a.sigla = 'FIPECQ' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'FMCPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'FOLHAPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'FORD' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'FORLUZ' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'FPMN' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'FRANCISCO CONDE' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'FRANPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'FUCAE' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'FUCAP' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'FUMAC' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'FUMPRESC' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERPE' AND a.sigla = 'FUNASA' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'FUNBEP' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERPE' AND a.sigla = 'FUNCASAL' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERDF' AND a.sigla = 'FUNCEF' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'FUNCESP' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'FUND. BRASILSAT' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'FUNDAÇÃO 14 PP' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'FUNDACAO COPEL' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'FUNDACAO CORSAN' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'FUNDAÇÃO LIBERTAS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'FUNDAMBRAS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERDF' AND a.sigla = 'FUNDIAGUA' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'FUNDO PARANA' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'FUNEPP' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'FUNGRAPA' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'FUNPADEPAR' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERDF' AND a.sigla = 'FUNPRESP-EXE' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERDF' AND a.sigla = 'FUNPRESP-JUD' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'FUNREDE' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'FUNSEJEM' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'FUNSSEST' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERDF' AND a.sigla = 'FUNTERRA' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'FUSAN' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'FUSESC' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'FUTURA II' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'FUTURA PREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'GAROTO' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'GASIUS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERDF' AND a.sigla = 'GEAP AUTOGESTÃO EM SAÚDE' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'GEBSA-PREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERDF' AND a.sigla = 'GEIPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'GERDAU' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'GOODYEAR' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERPE' AND a.sigla = 'GTMPREVI' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'GZM PREVI' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'HERINGPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERDF' AND a.sigla = 'IAJA' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'IBM' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'IBP' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'ICATUFMP' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'ICI CORAL' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'IFM' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'IJMS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'INDUSPREVI' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'INDUSPREVI-SUL' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERPE' AND a.sigla = 'INERGUS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'INFRAPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'INOVAR PREVIDENCIA' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'INSTITUTO AMBEV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'ISBRE' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'ISSS/SANDOZ' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'ITAU UNIBANCO' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'ITAUBANK' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'ITAUSAINDL' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'J & HIGGINS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'JOHNSON' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'JOSAPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'JUSPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'KPMG PREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'KRAFT PREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'LANXESSPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'LILLYPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'LOCPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'MAC LAREN' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'MAGNUS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'MAIS VIDA PREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'MANNESMANN' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'MAPPIN' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'MARCOPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'MARISOL' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'MAUA PREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'MBPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'MCPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'MENDESPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'MERCAPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'MERCERPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'MESSIUS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'METRUS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'MM PREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'MM PREVI' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'MONGERAL' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'MSD PREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'MULTIBRA' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'MULTIBRA INSTITUIDOR' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'MULTICOOP' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'MULTIPARANA' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'MULTIPENSIONS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'MULTIPLA' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'MULTIPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'MÚTUOPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'NALCOPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'NÉOS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'NOROESTE' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'NUCLEOS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'OABPREV-GO' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'OABPREV-MG' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERPE' AND a.sigla = 'OABPREVNORDESTE' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'OABPREV-PR' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'OABPREV-RJ' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'OABPREV-RS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'OABPREV-SC' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'OABPREV-SP' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'OESPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'ORIUS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'P&G PREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'PARSE' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'PEIXOTO' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PENA BRANCA' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'PETROS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PFIZER PREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'PHILIP MORRIS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PINUSPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PLANEJAR' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PLPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PORTOPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'PORTUS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERDF' AND a.sigla = 'POSTALIS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERPE' AND a.sigla = 'POTIPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERDF' AND a.sigla = 'POUPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'PREBEG' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'PRECE' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PREV PEPSICO' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERPE' AND a.sigla = 'PREVBEP' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PREVCAPCO' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PREVCHEVRON' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'PREVCOM-BRC' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'PREVCOM-MG' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'PREVCOOP' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PREVCUMMINS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'PREVDATA' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PREVDEUTSCHE' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PREVDOW' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PREVEME' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PREVEME II' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PREVER HAAS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PREVEREADY' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'PREVES' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PREVESTIRENO' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'PREVHAB' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PREVHENKEL' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERPE' AND a.sigla = 'PREVI - FIERN' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PREVI CIBA' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'PREVI GILLETTE' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'PREVI INCEPA' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PREVI NOVARTIS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'PREVI/BB' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PREVI/CIBA' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PREVIARMCO' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERPE' AND a.sigla = 'PREVIBAN' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'PREVI-BANERJ' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PREVIBAYER' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PREVIBENTONIT' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PREVIBOSCH' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PREVICAR' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PREVICAT' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'PREVICEL' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PREVI-CLARIANT' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'PREVICOKE' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PREVIDA' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'PREVIDÊNCIA USIMINAS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'PREVIDEXXONMOBIL' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PREVI-ERICSSON' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'PREVIFF' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'PREVIG' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PREVI-GM' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PREVIHONDA' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'PREVIK' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PREVIKODAK' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PREVILAVORO' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'PREVILEAF' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'PREVILIQUID' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PREVILLARES' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PREVILLOYDS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'PREVIM' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'PREVIMA' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'PREVIMAT' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'PREVINDUS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'PREVINOR' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERDF' AND a.sigla = 'PREVINORTE' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PREVIP' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PREVIPLAN' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PREVIQ' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'PREVIRB' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PREVIREFINACOES' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PREVISAO' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'PREVISC' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PREVISCANIA' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'PREVISERV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PREVI-SIEMENS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'PREVISTIHL' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PREVITDB' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'PREVITINTAS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PREVI-TOKYO' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERPE' AND a.sigla = 'PREVIVER' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PREVMILL' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PREVMOBIL' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PREVMON' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERDF' AND a.sigla = 'PREVMUTUA' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'PREVNORDESTE' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'PREVPISA' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'PREV-PR' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'PREVSAN' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PREVSOMPO' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PREVTOKIO' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'PREVUNIAO' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'PREVUNISUL' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PRHOSPER' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERPE' AND a.sigla = 'PRODUBAN' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PRO-FUTURO' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PROMON' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'PSS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'QUANTA' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'RAIZPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'RANDONPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'RBS PREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'REAL GRANDEZA' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'RECKITTPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'REFER' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERDF' AND a.sigla = 'REGIUS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'RENOPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'RESAPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'RIBEIRAO PREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'RIGEPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'RJPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'ROCHEPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'RS-PREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'RUMOS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'SABESPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'SANEPREVI' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'SANPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'SANTANDER BANES' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'SANTANDERPREVI' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'SAO BERNARDO' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERDF' AND a.sigla = 'SAO FRANCISCO' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'SAO RAFAEL' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERDF' AND a.sigla = 'SARAHPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'SBOTPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERDF' AND a.sigla = 'SBPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'SCHNEIDER' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'SCPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'SEAGRAM' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERDF' AND a.sigla = 'SEBRAE PREVIDENCIA' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'SEGURIDADE' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERPE' AND a.sigla = 'SERGUS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'SERPROS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'SIAS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERDF' AND a.sigla = 'SICOOB PREVI' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'SILIUS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'SINDPD' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'SINGER' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERDF' AND a.sigla = 'SISTEL' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'SITRATUH PREVIDÊNCIA' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERDF' AND a.sigla = 'SOCEPMI' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'SOMUPP' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'SP-PREVCOM' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'STEIO' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'SUL PREVIDÊNCIA' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'SULAMULTI' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'SULFABRILPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'SUPRE' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'SUPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'SWPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'SYNGENTA PREVI' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERDF' AND a.sigla = 'TECHNOS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'TELOS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'TETRA PAK PREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'TEXPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'TEXTIL PREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'TOYOTA PREVI' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'TRAMONTINAPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'TRICHESPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'UASPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'UBB-PREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'ULTRAPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'UNILEVERPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERMG' AND a.sigla = 'UNIPREVI' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'UNISYS-PREVI' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'URANUS' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'UTCPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'VALIA' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'VALUE PREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'VAN LEER' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'VBPP' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'VEXTY' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'VIKINGPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'VISÃO PREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERDF' AND a.sigla = 'VIVA' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'VOITH PREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRJ' AND a.sigla = 'VULCAPREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'VWPP' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERRS' AND a.sigla = 'WEG' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) UNION "+
" SELECT a.id, b.id FROM entidades a, escritorios b WHERE b.abreviatura = 'ERSP' AND a.sigla = 'WYETH PREV' AND NOT EXISTS (SELECT 1 FROM jurisdicoes c WHERE c.entidade_id = a.id AND c.escritorio_id = b.id) "